### ISSUE TITLE
stop eddy - go drink a beer

### ISSUE THREAD

**Issue by bradmartin** [EddyVerbruggen/nativescript-gradient#1]
https://github.com/bradmartin/nativescript-gradient

**Comment by EddyVerbruggen** [comment]
W000000t!

I was actually drinking a beer :)

Thanks for the heads up, honestly didn't see it. I've already got iOS done though (Android at 75%) and it supports an arbitrary number of colors instead of 2. Also, I'm not going to require additional libraries for both platforms.

Ant preference on how to proceed?

**Comment by bradmartin** [comment]
I like your style 🍺 .
Yea mine had 0 iOS support. The android side did use a native lib but not limited to colors - it just has a starting point/ending point (top left to bottom right and all variations of a square for a gradient). Ah you can take over the gradient if yours is gonna be x-plat and not add lib bloat 👍  . I've not transferred a package before on npm so need to figure that out but definitely can do.

**Comment by bradmartin** [comment]
Oh yea my old plugin is 2 colors - my bad. So yea yours is better - let's get yours to take over

**Comment by EddyVerbruggen** [comment]
Hey @bradmartin that would be very awesomely gentlemanlike of you!
I've just finished the plugin and am now working on a little demo (with and without Angular).

According to [the npm package ownership doc](https://docs.npmjs.com/cli/owner) it's just a few commands to remove and add ownership. Why not leave yourself as owner and add me `npm owner add eddyverbruggen nativescript-gradient`, then I'll add you as a contributor to this GitHub repo as well.

I will then finish the plugin and bump it to 2.0.0 to not bite current users of the npm package.

**Comment by EddyVerbruggen** [comment]
The plugin is ready, pretty happy with the code & result ;)

**Comment by bradmartin** [comment]
I'll ping you shortly to discuss the transfer

**Comment by EddyVerbruggen** [comment]
2.0.0 is now live on npm. Thanks Brad for the cooperation! 🤝
