### ISSUE TITLE
Can we use border-radius ?

### ISSUE THREAD

**Issue by MuhammadTahir92** [EddyVerbruggen/nativescript-gradient#17]

**Comment by MuhammadTahir92** [comment]
i use the way you ask @EddyVerbruggen  but the issue is its not working for button so that's why i reported this .

**Comment by EddyVerbruggen** [comment]
Perhaps that would have been nice to add to the empty description.

I guess you can recreate a button-like layout with the Gradient tag and some custom css. It is what it is.
