### ISSUE TITLE
The colors support transparency???

### ISSUE THREAD

**Issue by dianjuar** [EddyVerbruggen/nativescript-gradient#2]
Hi I wonder if the gradient colors support transparency.
To be more specific, I need do a gradient from black to transparent...

I need something like this.
![screen shot 2017-06-23 at 11 00 27](https://user-images.githubusercontent.com/7026066/27487917-310b4134-5803-11e7-8f82-5b53ec4d4e29.png)

But I have this.
![screen shot 2017-06-23 at 11 02 31](https://user-images.githubusercontent.com/7026066/27488013-8192b114-5803-11e7-9da6-a86c0b576720.png)

The code is:
```html
<GridLayout class="product-image">
  <Image [src]="productActual.image" stretch="aspectFill"></Image>
  <Gradient class="gadient-top" direction="to bottom" colors="#000000, #FFFFFF" verticalAlignment="top" > </Gradient>
</GridLayout>
````

**Comment by dianjuar** [comment]
### I DID IT!!!! I HACK IT!!!!

Viewing the attribute `colors` of `<Gradient>`, I saw there is a compatibility with the CSS colors.
I test it with `"red"` and `rgb(255, 0, 0)` and the result was the same, so I use `RGBA Colors` to get my transparency, I simple use `rgba(0, 0, 0, 0)` to get a full transparent color.

![screen shot 2017-06-23 at 11 19 40](https://user-images.githubusercontent.com/7026066/27488680-e3ebb53e-5805-11e7-8930-f24fe9a3e708.png)

```html
<GridLayout class="product-image">
  <Image [src]="productActual.image" stretch="aspectFill"></Image>
  <Gradient class="gadient-top" direction="to bottom" colors="#000000, rgba(0, 0, 0, 0)" verticalAlignment="top" > </Gradient>
</GridLayout>
```

--------------------

Maybe in your readme, in the __usage_ section tell that your colors definitions are compatible with [CSS Colors](https://www.w3schools.com/cssref/css_colors_legal.asp)

**Comment by jogboms** [comment]
@dianjuar Thats a really cool trick.

**Comment by EddyVerbruggen** [comment]
Hey @dianjuar, nice job!

It was mentioned in the readme that anything you can pass to NativeScript's `new Color(...)` constructors would work, but [I've now made it more clear](https://github.com/EddyVerbruggen/nativescript-gradient/blob/master/README.md#usage).
