### ISSUE TITLE
[Question] Is it possible to add the gradient to a button?

### ISSUE THREAD

**Issue by uioporqwerty** [EddyVerbruggen/nativescript-gradient#5]
I was trying to add the gradient to a button but it adds it to the entire container since `Gradient` functions like `StackLayout`. Wondering how it would be possible to apply it to a specific element type without taking up the full width / height of the container.

**Comment by uioporqwerty** [comment]
Figured out that it is possible to do this by shrinking the container to the button size and then having the button take up the full container size. However, applying border-radius on the Gradient makes it completely disappear, why might that be?

**Comment by EddyVerbruggen** [comment]
For example `borderRadius="5"` now works, with version 2.0.1.
