### ISSUE TITLE
Gradient orientation: radial

### ISSUE THREAD

**Issue by HighSoftWare96** [EddyVerbruggen/nativescript-gradient#6]

**Comment by EddyVerbruggen** [comment]
Are you going to create a PR to add that? I'm not sure what you mean..

**Comment by HighSoftWare96** [comment]
Sorry, I mean: there is the possibility to create a radial gradient?

**Comment by EddyVerbruggen** [comment]
No there is currently not, only linear in any direction you want with as many colors as you like, but there's no radial option at the moment.

Perhaps in the future but it's not planned.

**Comment by HighSoftWare96** [comment]
Ok thanks!
