### ISSUE TITLE
Use Gradient over image

### ISSUE THREAD

**Issue by SanchitSolulab** [EddyVerbruggen/nativescript-gradient#9]
How can I make it possible to use it with an image? I want the gradient to appear on the bottom of the image. Something like the attached image.

![image](https://user-images.githubusercontent.com/22098426/30261942-75cabaca-96ec-11e7-93c5-53323964893e.png)

**Comment by EddyVerbruggen** [comment]
Interesting question!

With the current plugin implementation it seems like it's easiest to make those UI overlap each other by using a `GridLayout` without specifying row indexes.

See the updated screenshots in the readme (I pasted it here as well), and use a snippet [like this](https://github.com/EddyVerbruggen/nativescript-gradient/blob/34eb76fe04531e8dd62485e4dc1c166666085e73/demo/app/main-page.xml#L22-L26).

![ios-partial2](https://user-images.githubusercontent.com/1426370/30262756-6e4081a0-96d2-11e7-849c-54f8569f962f.png)
